# Generated by Django 5.2.17 on 2026-09-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('groups', '0001_initial'),
        ('odk', '0001_initial'),
        ('senders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign_type', models.CharField(choices=[('STANDARD', 'Standard Email Campaign'), ('SURVEY_REMINDER', 'Survey Campaign with Automated Reminders')], default='SURVEY_REMINDER', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('completion_status_source', models.CharField(default='ODK_CENTRAL', max_length=50)),
                ('initial_recipient_rule', models.CharField(choices=[('UNUSED_ONLY', 'Unused contacts only'), ('ALL_VALID', 'All selected valid contacts')], default='UNUSED_ONLY', max_length=30)),
                ('subject', models.CharField(max_length=500)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='campaigns', to='groups.contactgroup')),
                ('odk_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='odk.odkform')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='senders.sender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('INITIAL', 'Initial Email'), ('REMINDER', 'Reminder Email'), ('TEST', 'Test Email')], default='INITIAL', max_length=20)),
                ('reminder_sequence', models.PositiveIntegerField(default=0, help_text='0 for initial, 1 for reminder 1, 2 for reminder 2...')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('SOFT_BOUNCE', 'Soft Bounce'), ('HARD_BOUNCE', 'Hard Bounce'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('skip_reason', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_messages', to='contacts.contact')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_407020_idx'), models.Index(fields=['contact', 'status'], name='campaigns_c_contact_59824f_idx'), models.Index(fields=['provider_message_id'], name='campaigns_c_provide_eb0c7c_idx')],
                'unique_together': {('campaign', 'contact', 'message_type', 'reminder_sequence')},
            },
        ),
    ]
