# Generated by Django 5.2.17 on 2026-09-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_odk_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='batch_interval_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='batch_size',
            field=models.PositiveIntegerField(blank=True, default=50, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='send_mode',
            field=models.CharField(choices=[('IMMEDIATE', 'Send Now'), ('SCHEDULED', 'Schedule for later'), ('BATCHES', 'Send in Batches'), ('DRAFT', 'Draft')], default='IMMEDIATE', max_length=20),
        ),
    ]
