# Generated by Django 5.2.17 on 2026-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_batch_interval_minutes_campaign_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='destination_url',
            field=models.TextField(blank=True, default='', help_text="Default destination URL (http:// or https://) used by this campaign's shareable tracking links."),
        ),
    ]
