# Generated by Django 5.2.17 on 2026-09-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('URL', 'URL')], default='TEXT', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('login_password_encrypted', models.TextField(blank=True)),
                ('job_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('UNUSED', 'Unused'), ('USED', 'Used')], db_index=True, default='UNUSED', max_length=20)),
                ('email_status', models.CharField(choices=[('Active', 'Active'), ('Invalid', 'Invalid'), ('Unsubscribed', 'Unsubscribed'), ('Soft Bounce', 'Soft Bounce'), ('Hard Bounce', 'Hard Bounce'), ('Blocked', 'Blocked')], db_index=True, default='Active', max_length=30)),
                ('odk_submission_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('odk_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('odk_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('status_source', models.CharField(default='MANUAL', max_length=50)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed', models.BooleanField(db_index=True, default=False)),
                ('bounce_status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='contacts_co_email_25f973_idx'), models.Index(fields=['job_id'], name='contacts_co_job_id_a89b08_idx'), models.Index(fields=['status'], name='contacts_co_status_d675ed_idx'), models.Index(fields=['email_status'], name='contacts_co_email_s_e1c331_idx'), models.Index(fields=['unsubscribed'], name='contacts_co_unsubsc_c73efc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=50)),
                ('odk_submission_id', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contacts.contact')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='contacts.contact')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='contacts.contactcustomfield')),
            ],
            options={
                'unique_together': {('contact', 'field')},
            },
        ),
    ]
