# Generated by Django 5.2.17 on 2026-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=500),
        ),
    ]
