# Generated by Django 5.2.17 on 2026-09-09 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('email_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_value', models.PositiveIntegerField(default=2, help_text='e.g. 2')),
                ('interval_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks')], default='DAYS', max_length=20)),
                ('duration_value', models.PositiveIntegerField(default=3, help_text='e.g. 3')),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks')], default='WEEKS', max_length=20)),
                ('max_reminders', models.PositiveIntegerField(default=10)),
                ('sync_odk_before_send', models.BooleanField(default=True, help_text='Always sync ODK Central before running reminder')),
                ('stop_when_used', models.BooleanField(default=True, help_text='Immediately stop sending reminders once contact status is USED')),
                ('custom_subject', models.CharField(blank=True, help_text='e.g. Reminder: Complete your survey - {{job_id}}', max_length=500)),
                ('custom_html_content', models.TextField(blank=True)),
                ('reminders_sent_count', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_config', to='campaigns.campaign')),
                ('reminder_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_templates.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField()),
                ('scheduled_for', models.DateTimeField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCING_ODK', 'Syncing ODK'), ('QUEUED', 'Queued'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('opened_count', models.PositiveIntegerField(default=0)),
                ('became_used_count', models.PositiveIntegerField(default=0)),
                ('still_unused_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('reminder_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='reminders.reminderconfiguration')),
            ],
            options={
                'ordering': ['cycle_number'],
                'unique_together': {('reminder_config', 'cycle_number')},
            },
        ),
    ]
