# Generated by Django 5.2.17 on 2026-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactgroup',
            name='field_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Stored mapping configuration from ODK or file import'),
        ),
        migrations.AddField(
            model_name='contactgroup',
            name='selected_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of active field keys for this group'),
        ),
    ]
