# Generated by Django 5.2.17 on 2026-09-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_job_id'),
        ('groups', '0002_contactgroup_field_mappings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean (Yes/No)'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('URL', 'URL'), ('SELECT', 'Dropdown Select')], default='TEXT', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for SELECT type fields')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='groups.contactgroup')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('group', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='GroupContactValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_custom_values', to='contacts.contact')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='groups.groupcustomfield')),
            ],
            options={
                'unique_together': {('contact', 'field')},
            },
        ),
    ]
