# Generated by Django 5.2.17 on 2026-09-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcustomfield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active fields are shown as columns in the contacts table and in add/edit modals'),
        ),
    ]
