# Generated by Django 5.2.17 on 2026-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_add_is_active_to_group_custom_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Core QA Team, Executive Review', max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('emails', models.TextField(help_text='Comma, semicolon, or newline-separated list of test email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
