# Generated by Django 5.2.17 on 2026-09-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_batch_interval_minutes_campaign_batch_size_and_more'),
        ('contacts', '0002_alter_contact_job_id'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(help_text='Target destination URL (http:// or https://)')),
                ('link_name', models.CharField(blank=True, help_text='Human readable link label (e.g. ODK Survey Link)', max_length=255)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortened_links', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'shortened_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_token', models.CharField(db_index=True, max_length=16, unique=True)),
                ('short_url', models.CharField(max_length=500)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('human_click_count', models.PositiveIntegerField(default=0)),
                ('bot_click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='contacts.contact')),
                ('shortened_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='tracking.shortenedlink')),
            ],
            options={
                'db_table': 'recipient_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('click_type', models.CharField(choices=[('HUMAN', 'Human'), ('SUSPECTED_BOT', 'Suspected Bot'), ('UNKNOWN', 'Unknown')], db_index=True, default='HUMAN', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_click_events', to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='link_click_events', to='contacts.contact')),
                ('recipient_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='tracking.recipientlink')),
            ],
            options={
                'db_table': 'link_click_events',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['campaign', 'clicked_at'], name='link_click__campaig_88500d_idx'), models.Index(fields=['contact', 'clicked_at'], name='link_click__contact_31b3e5_idx'), models.Index(fields=['click_type', 'clicked_at'], name='link_click__click_t_51bba2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='recipientlink',
            index=models.Index(fields=['tracking_token'], name='recipient_l_trackin_ef700e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientlink',
            index=models.Index(fields=['campaign', 'contact'], name='recipient_l_campaig_244825_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientlink',
            index=models.Index(fields=['campaign', 'shortened_link'], name='recipient_l_campaig_93f6b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipientlink',
            unique_together={('shortened_link', 'contact', 'campaign')},
        ),
    ]
