# Generated by Django 5.2.17 on 2026-09-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_destination_url'),
        ('tracking', '0002_shortenedlink_recipientlink_linkclickevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Human readable label (e.g. Facebook Ad, Website Banner)', max_length=255)),
                ('tracking_token', models.CharField(db_index=True, max_length=16, unique=True)),
                ('short_url', models.CharField(max_length=500)),
                ('destination_url', models.TextField(blank=True, default='', help_text='Destination URL (http:// or https://). Blank = use campaign default.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('human_click_count', models.PositiveIntegerField(default=0)),
                ('bot_click_count', models.PositiveIntegerField(default=0)),
                ('first_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_links', to='campaigns.campaign')),
            ],
            options={
                'db_table': 'campaign_tracking_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLinkClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('click_type', models.CharField(choices=[('HUMAN', 'Human'), ('SUSPECTED_BOT', 'Suspected Bot'), ('UNKNOWN', 'Unknown')], db_index=True, default='HUMAN', max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_link_click_events', to='campaigns.campaign')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='tracking.campaigntrackinglink')),
            ],
            options={
                'db_table': 'campaign_link_click_events',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaigntrackinglink',
            index=models.Index(fields=['campaign', 'is_active'], name='campaign_tr_campaig_a97016_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlinkclickevent',
            index=models.Index(fields=['campaign', 'clicked_at'], name='campaign_li_campaig_bfe780_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlinkclickevent',
            index=models.Index(fields=['click_type', 'clicked_at'], name='campaign_li_click_t_456b29_idx'),
        ),
    ]
