# Generated by Django 5.2.17 on 2026-09-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_destination_url'),
        ('contacts', '0002_alter_contact_job_id'),
        ('tracking', '0003_campaigntrackinglink_campaignlinkclickevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlinkclickevent',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Set for recipient-link visits; NULL for anonymous shareable visits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_link_click_events', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='campaigntrackinglink',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Recipient this link was generated for (recipient links only).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tracking_links', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='campaigntrackinglink',
            name='link_type',
            field=models.CharField(choices=[('SHAREABLE', 'Shareable / Anonymous'), ('RECIPIENT', 'Recipient')], db_index=True, default='SHAREABLE', help_text='SHAREABLE = owner-generated anonymous link; RECIPIENT = per-contact email link.', max_length=16),
        ),
        migrations.AddField(
            model_name='campaigntrackinglink',
            name='shortened_link',
            field=models.ForeignKey(blank=True, help_text='Groups recipient links by destination URL (recipient links only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_tracking_links', to='tracking.shortenedlink'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntrackinglink',
            unique_together={('shortened_link', 'contact', 'campaign')},
        ),
        migrations.AddIndex(
            model_name='campaignlinkclickevent',
            index=models.Index(fields=['contact', 'clicked_at'], name='campaign_li_contact_d3675f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntrackinglink',
            index=models.Index(fields=['campaign', 'link_type'], name='campaign_tr_campaig_b50916_idx'),
        ),
    ]
