# Generated by Django 5.2.17 on 2026-09-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ODKConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. IRIS ODK Central or Research Server', max_length=255)),
                ('base_url', models.URLField(help_text='e.g. https://odk.company.com or http://localhost:8000/sandbox/odk')),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_or_token_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mock_sandbox', models.BooleanField(default=False, help_text='If True, queries internal sandbox submission table')),
                ('status', models.CharField(choices=[('UNTESTED', 'Untested'), ('CONNECTED', 'Connected'), ('FAILED', 'Failed')], default='UNTESTED', max_length=20)),
                ('last_connection_test', models.DateTimeField(blank=True, null=True)),
                ('last_test_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ODKForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odk_xml_form_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_submission_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_submission_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ODKFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id_field', models.CharField(default='job_id', help_text='ODK schema field that holds Contact JobID', max_length=100)),
                ('email_field', models.CharField(blank=True, default='email', max_length=100)),
                ('phone_field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_mapping', to='odk.odkform')),
            ],
        ),
        migrations.CreateModel(
            name='ODKProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odk_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='odk.odkconnection')),
            ],
            options={
                'unique_together': {('connection', 'odk_id')},
            },
        ),
        migrations.AddField(
            model_name='odkform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='odk.odkproject'),
        ),
        migrations.CreateModel(
            name='ODKSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('trigger_source', models.CharField(choices=[('MANUAL', 'Manual Click'), ('SCHEDULED', 'Scheduled Interval'), ('PRE_REMINDER', 'Pre-Reminder Check')], default='MANUAL', max_length=30)),
                ('submissions_checked', models.PositiveIntegerField(default=0)),
                ('new_submissions', models.PositiveIntegerField(default=0)),
                ('contacts_marked_used', models.PositiveIntegerField(default=0)),
                ('unmatched_job_ids', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='odk.odkconnection')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='odk.odkform')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ODKUnmatchedSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=255)),
                ('job_id_value', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('sync_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unmatched_submissions', to='odk.odksyncjob')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='odkform',
            unique_together={('project', 'odk_xml_form_id')},
        ),
    ]
