# Generated by Django 5.2.17 on 2026-09-09 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ODKDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('entities_count', models.PositiveIntegerField(default=0)),
                ('last_entity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='odk.odkproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ODKEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('server_created_at', models.DateTimeField(blank=True, null=True)),
                ('server_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='odk.odkdataset')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('dataset', 'uuid')},
            },
        ),
    ]
