# Generated by Django 5.2.17 on 2026-09-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0002_odkdataset_odkentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='odkdataset',
            name='unused_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='odkdataset',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='odkentity',
            name='status',
            field=models.CharField(db_index=True, default='UNUSED', max_length=20),
        ),
    ]
