# Generated by Django 5.2.17 on 2026-09-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly sender name e.g. IRIS Communications', max_length=255)),
                ('email', models.EmailField(help_text='Sender email address e.g. survey@company.com', max_length=254)),
                ('reply_to', models.EmailField(blank=True, help_text='Optional reply-to address', max_length=254)),
                ('provider_type', models.CharField(choices=[('SANDBOX', 'Internal Sandbox / Webmail Simulator'), ('SMTP', 'Custom SMTP'), ('BREVO', 'Brevo (Sendinblue) API'), ('AMAZON_SES', 'Amazon SES API'), ('MAILGUN', 'Mailgun API'), ('SENDGRID', 'SendGrid API'), ('POSTMARK', 'Postmark API')], default='SANDBOX', max_length=30)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_or_key_encrypted', models.TextField(blank=True)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('api_domain', models.CharField(blank=True, help_text='For Mailgun domain or Brevo endpoint', max_length=255)),
                ('api_region', models.CharField(blank=True, default='us-east-1', help_text='For AWS SES region', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.PositiveIntegerField(default=80000)),
                ('hourly_limit', models.PositiveIntegerField(default=3000)),
                ('per_minute_limit', models.PositiveIntegerField(default=50)),
                ('today_sent', models.PositiveIntegerField(default=0)),
                ('this_hour_sent', models.PositiveIntegerField(default=0)),
                ('this_minute_sent', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
