# Generated by Django 5.2.17 on 2026-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='disable_provider_click_tracking',
            field=models.BooleanField(default=False, help_text='Ask the provider to skip its own click-link rewriting (SendGrid/Mailgun/Postmark). Our tracking stays active. No effect on Brevo, which offers no API opt-out.'),
        ),
    ]
