# Generated by Django 5.2.17 on 2026-09-09 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/')),
                ('file_type', models.CharField(default='CSV', max_length=10)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('duplicate_strategy', models.CharField(choices=[('SKIP', 'Skip duplicates'), ('UPDATE', 'Update existing contacts'), ('ADD_TO_GROUP', 'Add existing contacts to group')], default='UPDATE', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_contacts', models.PositiveIntegerField(default=0)),
                ('new_contacts', models.PositiveIntegerField(default=0)),
                ('existing_contacts', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('invalid_emails', models.PositiveIntegerField(default=0)),
                ('missing_emails', models.PositiveIntegerField(default=0)),
                ('missing_job_ids', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANALYZED', 'Analyzed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.contactgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
